name: linter
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out repository code
        uses: actions/setup-python@v2
      - name: make lint
        run: poetry run flake8 brain_games