name: linter
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out repository code
        uses: actions/setup-python@v2
      - name: Lint with flake8
        run: pip install flake8 | flake8 brain_games