name: linter
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install Linter
        run: pip install flake8
      - name: Run Linter
        run: make lint